/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

struct struct_func{

    uint16_t cmd;
    uint16_t data;
};
 struct struct_func gc9a01[] = {
		{0x01, 0x02},
		{0x04, 0x03},
};

int main(void)
{
    /* Loop forever */


	int g = 0;
	g = gc9a01[1].cmd;

	for(;;);
}
